### ISSUE TITLE
Feature request: show color map

### ISSUE THREAD

**Issue by VikingScientist** [TheBB/Geomaker#22]
The current list of color maps is quite long and impressive, but too long from a usability perspective. I would like to see a preview of the color range in addition to the name and also preferably group them into topics. For instance "Diverging", "Cyclic", "Qualitative", "Sequential" etc.

**Comment by TheBB** [comment]
Right now it's just a list of whatever is in matplotlib. Agree that it's not very useful but it was at least quick and dirty.

**Comment by VikingScientist** [comment]
I love it! :heart:
