### ISSUE TITLE
Help wanted: is the Export button sensitive to which tab I have open?

### ISSUE THREAD

**Issue by VikingScientist** [TheBB/Geomaker#24]
I can only seem to press the export button when I have the NIB tab selected. It is grayed out when I have other elevation models selected. If it makes a difference then I only have "old" elevation models. That is data which was created at 160e9332f63ee184cfb1acddb90ab001fc3370b0. I can't seem to make new data due to issue #23 .

My question is how the export button works. Does it makes sense to export a vtk or g2 model from NIB? It seem to be an option, but I don't know what its going to produce if so. How do I download the NIB-export? From the data it seems that you have to choose exterior or interior angle?

**Comment by TheBB** [comment]
Yes, it exports data from the tab you have open. Have you deleted your old database? If not, could you, and try #23 again?

Some export options should be disabled with the NIB project, that's right. Currently that doesn't happen. You should get some sort of numpy shape error if you try to do it.

> How do I download the NIB-export? From the data it seems that you have to choose exterior or interior angle?

What do you mean? It'll work as a texture if you do smallest exterior rectangle with axis-aligned (zero) rotation.

**Comment by VikingScientist** [comment]
> > How do I download the NIB-export? From the data it seems that you have to choose exterior or interior angle?
> 
> What do you mean? It'll work as a texture if you do smallest exterior rectangle with axis-aligned (zero) rotation.

What I don't understand is how the texture from NIB is put to the right place. I haven't gotten the converter to properly work yet due to my problems with downloading the data in the first place (see #23 ). My current guess (since the crop functionality is grayed out) is that vtk and stl prooduces the full (slightly rotated) geometry since you can do (x,y,z)-coordinates for all datapoints, while the texture export (png or jpg) needs to do a perfect rectangle and thus have to return bounding-box or largest interior rectangle.

**Comment by TheBB** [comment]
Points outside the polygon in the NIB texture will be black. But they shouldn't show in the texture. The texture coordinates in the VTK file indicates which pixels apply to which points. STL files don't support included texture coordinates, so there you are at the mercy of Paraview automatically doing the right thing.

But we can revisit when we get the other stuff working.

**Comment by TheBB** [comment]
Okay, now that I'm pretty sure data download still works:

If you export a VTK or VTU file and you have the 'include texture coordinates' checkbox checked, the generated file will include not just x, y, z but also u and v coordinates. When you apply a texture, Paraview uses u and v for each point to figure out which part of the image goes where.

To generate an image that fits with the u, v coordinates, you should choose 
- the same coordinate system as the VTK/VTU file (UTM33N typically)
- smallest exterior rectangle
- axis aligned rotation

It doesn't say anywhere that these are the magic choices. I wanted to add a specialized texture export option so the user wouldn't have to know about it. But for now you must. :-)

The smallest exterior + axis aligned option will produce an image that is 'too large' and has black parts. This should be fine because there shouldn't be any points in the VTK/VTU file with u,v coordinates pointing to those parts.

**Comment by TheBB** [comment]
After #28 the project is shown in the export dialog (defaulting to the current open tab).

**Comment by VikingScientist** [comment]
I do get a verification email that the data is available, but the software spits out the following error message

```
Traceback (most recent call last):
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/asynchronous.py", line 220, in process
    result = self.job.process(self)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/asynchronous.py", line 371, in process
    job.process(manager, *args, **kwargs)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/asynchronous.py", line 401, in process
    retval = job.process(manager, retval)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/asynchronous.py", line 385, in process
    return self.job.process(manager, arg)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/asynchronous.py", line 355, in process
    retval = self.func(*args, **kwargs, manager=manager)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/db.py", line 629, in _download_data
    filename = hashlib.sha256(data).hexdigest() + '.tiff'
NameError: name 'data' is not defined
```

**Comment by TheBB** [comment]
Oops, sorry, just fixed it.

I stopped downloading dedicated files so it went unnoticed for a while.

**Comment by VikingScientist** [comment]
Is probably way off tangent of wheter these things are related to the original issue description, but I got a new error message for you

```Traceback (most recent call last):
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/asynchronous.py", line 220, in process
    result = self.job.process(self)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/asynchronous.py", line 371, in process
    job.process(manager, *args, **kwargs)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/asynchronous.py", line 401, in process
    retval = job.process(manager, retval)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/asynchronous.py", line 355, in process
    retval = self.func(*args, **kwargs, manager=manager)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/db.py", line 379, in _update_thumbnail
    filename = export.export(self, project, manager, maxpts=640, directory=filesystem.THUMBNAIL_ROOT)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/export.py", line 206, in export
    data = polygon.interpolate(project, in_x, in_y)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/db.py", line 365, in interpolate
    datafile.interpolate(data, mask, x, y)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/db.py", line 456, in interpolate
    data[m] += refdata[il, jl] * ((1 - (xl - il)) * (1 - (yl - jl)))[:, np.newaxis]
IndexError: index 798 is out of bounds for axis 1 with size 798

```

**Comment by TheBB** [comment]
That one is harder for me to check but I can push a commit that produces a more sensible error message that can help me fix it.

**Comment by TheBB** [comment]
Actually, I was able to repro it with a dedicated file. 'ang on

**Comment by TheBB** [comment]
Should be fixed now.

**Comment by VikingScientist** [comment]
Confirmed fixed
