### ISSUE TITLE
Help wanted: how do I specify free rotation parameters?

### ISSUE THREAD

**Issue by VikingScientist** [TheBB/Geomaker#40]
In the export data when specifying "free rotation". How do specify the rotation in question? Correct me if I'm wrong, but currently it doesn't appear to do anything.

![Export data_009](https://user-images.githubusercontent.com/3500376/75019890-f7a50680-5491-11ea-865c-08f181ea7ee3.png)

**Comment by TheBB** [comment]
It'll compute the rotation that minimizes the area discrepancy. Click the recompute button.

I guess it should be named automatic rotation or something.

**Comment by VikingScientist** [comment]
Ah... this was not obvious. All 5 of these options could benefit from an explination picture, but that might be hard to integrate directly into the UI. I'm going to open an issue requesting hover tooltips on these. 

I'm assuming "axis-aligned" means that it is aligned according to the UTM33 axes, while "north-aligned" means its using lat/lon coordinate system, or at least that positive y-coordinates point straight north.

**Comment by TheBB** [comment]
More precisely, axis-aligned means that you get a rectangle whose sides are aligned with the axes in the coordinate system you specify. North-aligned means that you get a rectangle whose sides are aligned with the compass, or at least approximately so: the NESW directions are not guaranteed to be everywhere the same.

**Comment by VikingScientist** [comment]
Duplicate of #43
