### ISSUE TITLE
Feature Request: ability to rename areas

### ISSUE THREAD

**Issue by VikingScientist** [TheBB/Geomaker#7]
Double-clicking the name in the list of "stored regions" should open up the possibility to rename the region in question.

This one has really low priority, but if time permits, this would be nice.

**Comment by TheBB** [comment]
It's possible to rename if you click the already selected item (which is not exactly the same thing as double-clicking) or by pressing F2.

Double-clicking instead moves and zooms the map view to the given region.

**Comment by VikingScientist** [comment]
Would you look at that :smile:  Great thanks. This is sufficient :+1:
